---
- hosts: webservers
  become: true
  gather_facts: no
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: start apache
      service:
        name: httpd
        state: started
        enabled: True
     - name: start apache
      service:
        name: httpd
        state: restarted
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
